import Head from "next/head";
import styles from "@/styles/Home.module.css";

import MainLayout from "@/layouts/mainLayout";
import Card from "@/components/card";

import { getAllPosts } from "@/utils/post";

export default function Home({ postData }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className={styles.cardList}>
          {postData?.map((post, index) => (
            <Card key={index} data={post} />
          ))}
        </div>
      </MainLayout>
    </>
  );
}

export const getStaticProps = () => {
  const postData = getAllPosts();

  return {
    props: {
      postData,
    },
  };
};
